import assert from 'node:assert/strict';
import {test} from 'node:test';
process.env.NEXT_PUBLIC_STATIC_HOSTING='true';
const {fetchForecast,searchPlaces}=await import('../lib/weather-client.ts');
const controller=new AbortController();
const raw={timezone:'UTC',current:{time:'2026-09-09T09:00',temperature_2m:22,apparent_temperature:22,weather_code:0,is_day:1},daily:{time:['2026-09-09','2026-09-10']},hourly:{time:['2026-09-09T09:00'],temperature_2m:[22],apparent_temperature:[22],precipitation_probability:[10],precipitation:[0],wind_speed_10m:[5],weather_code:[0],is_day:[1]}};
test('Pages fetches directly from the provider and caches a successful result',async()=>{let calls=0;const previous=globalThis.fetch;globalThis.fetch=async url=>{calls++;assert.equal(url.origin,'https://api.open-meteo.com');assert.equal(url.searchParams.get('timezone'),'auto');return Response.json(raw);};try{const p={name:'Test',latitude:1,longitude:2};const f=await fetchForecast(p,controller.signal);assert.equal(f.hours[0].temp,22);assert.equal(f.hours[0].daylight,true);await fetchForecast(p,controller.signal);assert.equal(calls,1);}finally{globalThis.fetch=previous;}});
test('Pages city search uses geocoding without a hosted API route',async()=>{const previous=globalThis.fetch;globalThis.fetch=async url=>{assert.equal(url.origin,'https://geocoding-api.open-meteo.com');assert.equal(url.searchParams.get('name'),'London');return Response.json({results:[{name:'London',latitude:51.5,longitude:-.12}]});};try{assert.equal((await searchPlaces('London',controller.signal))[0].name,'London');}finally{globalThis.fetch=previous;}});
test('failed and incomplete responses never become a forecast',async()=>{const previous=globalThis.fetch;try{globalThis.fetch=async()=>new Response('',{status:503});await assert.rejects(fetchForecast({name:'Failure',latitude:3,longitude:4},controller.signal),/update/);globalThis.fetch=async()=>Response.json({...raw,hourly:{...raw.hourly,temperature_2m:[null]}});await assert.rejects(fetchForecast({name:'Incomplete',latitude:5,longitude:6},controller.signal),/incomplete/);}finally{globalThis.fetch=previous;}});
