'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { CloudSun, CloudRain, Cloud, Moon, Sun, Snowflake, MapPin, LocateFixed, Umbrella, Shirt, Sunset, ArrowUpRight, RefreshCw, Clock3, ChevronDown } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Combobox, ComboboxInput, ComboboxContent, ComboboxList, ComboboxItem, ComboboxEmpty } from '@/components/ui/combobox';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { fetchForecast, searchPlaces } from '@/lib/weather-client';
import type { CSSProperties } from 'react';
import { defaultPlace, interpret, conditions, hourLabel, type Forecast, type Place } from '@/lib/weather';

const label=(p:Place)=>[p.name,p.admin1,p.country].filter(Boolean).join(', ');
function localNow(timezone:string,now:number){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now);const p=Object.fromEntries(parts.map(v=>[v.type,v.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
export default function Home(){
 const [place,setPlace]=useState<Place>(defaultPlace),[forecast,setForecast]=useState<Forecast|null>(null),[day,setDay]=useState('0'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[geoError,setGeoError]=useState(''),[locating,setLocating]=useState(false);
 const [query,setQuery]=useState(''),[results,setResults]=useState<Place[]>([]),[searchStatus,setSearchStatus]=useState('Type a city name'),[now,setNow]=useState(Date.now());
 const requestId=useRef(0),abort=useRef<AbortController|null>(null);
 const load=useCallback(async(p:Place,reset=false)=>{const id=++requestId.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setLoading(true);setError('');if(reset){setForecast(null);setDay('0');}try{const data=await fetchForecast(p,controller.signal);if(id===requestId.current){setForecast(data);setNow(Date.now());}}catch(e){if(id===requestId.current&&!controller.signal.aborted)setError(e instanceof Error?e.message:'Forecast unavailable');}finally{if(id===requestId.current)setLoading(false);}},[]);
 useEffect(()=>{void load(place,true);const t=setInterval(()=>{if(!document.hidden)void load(place);},900000);const focus=()=>{if(!document.hidden)void load(place);};document.addEventListener('visibilitychange',focus);return()=>{clearInterval(t);document.removeEventListener('visibilitychange',focus);abort.current?.abort();};},[place,load]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(t);},[]);
 useEffect(()=>{const controller=new AbortController();if(query.trim().length<2){setResults([]);setSearchStatus('Type at least two letters');return;}setSearchStatus('Searching…');const t=setTimeout(async()=>{try{const places=await searchPlaces(query,controller.signal);setResults(places);setSearchStatus(places.length?'':'No cities found. Try a nearby city.');}catch(e){if(!controller.signal.aborted){setResults([]);setSearchStatus(e instanceof Error?e.message:'Search unavailable');}}},300);return()=>{controller.abort();clearTimeout(t);};},[query]);
 const choose=(p:Place)=>{setPlace(p);setGeoError('');setQuery('');setResults([]);};
 const locate=()=>{setGeoError('');if(!navigator.geolocation){setGeoError('Location isn’t supported here. Search for your city.');return;}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{choose({name:'Your location',latitude:p.coords.latitude,longitude:p.coords.longitude});setLocating(false);},()=>{setLocating(false);setGeoError('Location access wasn’t available. Search for your city instead.');},{timeout:10000,maximumAge:300000});};
 const local=forecast?localNow(forecast.timezone,now):'';
 const advice=useMemo(()=>forecast?interpret(forecast,Number(day),local):null,[forecast,day,local]);
 const stale=Boolean(forecast&&(now-Date.parse(forecast.fetchedAt)>30*60000||error||forecast.dates[0]!==local.slice(0,10)));
 const sky=advice?.sky||'cloudy';const WeatherIcon=sky==='night'?Moon:sky==='rain'?CloudRain:sky==='clear'?Sun:sky==='snow'?Snowflake:Cloud;
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
  const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;
  const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_weather_advice',description:'Read the currently displayed True Weather forecast and practical advice, with its location and freshness.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');return{location:label(place),day:day==='0'?'today':'tomorrow',loading,stale,updatedAt:forecast?.fetchedAt||null,advice,error};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[place,day,loading,stale,forecast,advice,error]);
 return <main className="weather-app" data-sky={sky} style={{'--sky-image':`url("${process.env.NEXT_PUBLIC_BASE_PATH||''}/weather-sky.png")`} as CSSProperties}><div className="sky" aria-hidden="true"/><div className="shell">
 <header className="header"><div className="brand"><CloudSun aria-hidden="true"/>true weather<ArrowUpRight aria-hidden="true" style={{width:16}}/></div><span className="version">EARLY ACCESS</span></header>
 <div className="location-bar"><div><h1 className="location-name"><MapPin aria-hidden="true"/>{place.name}</h1><div className="muted">{forecast?new Intl.DateTimeFormat('en',{timeZone:forecast.timezone,weekday:'long',month:'short',day:'numeric'}).format(now):'Today + tomorrow'}{place.country?` · ${place.country}`:''}</div></div>
 <div className="location-actions"><div className="search-wrap"><Combobox items={results} filter={null} itemToStringLabel={label} onInputValueChange={setQuery} onValueChange={p=>{if(p)choose(p as Place);}}><ComboboxInput aria-label="Search for a city" placeholder="Search a city" showTrigger={false}/><ComboboxContent className="place-popup"><ComboboxEmpty>{searchStatus}</ComboboxEmpty><ComboboxList>{(p:Place)=><ComboboxItem key={p.id??label(p)} value={p}><span>{p.name}<small>{[p.admin1,p.country].filter(Boolean).join(', ')}</small></span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div><button className="quiet-button" onClick={locate} disabled={locating} aria-label="Use my location"><LocateFixed/><span className="locate-label">{locating?'Locating…':'Use my location'}</span></button></div></div>
 {geoError&&<div className="status" role="alert">{geoError}</div>}
 {(error||stale)&&<div className="status" role="alert"><span>{forecast?'Showing an older forecast. Advice may have changed.':error}</span><button className="quiet-button" disabled={loading} onClick={()=>load(place)}><RefreshCw/>Retry</button></div>}
 {forecast&&advice?<div className="day-tabs"><Tabs value={day} onValueChange={v=>setDay(String(v))}><TabsList variant="line" aria-label="Forecast day"><TabsTrigger value="0">Today</TabsTrigger><TabsTrigger value="1">Tomorrow</TabsTrigger></TabsList>{['0','1'].map(v=><TabsContent key={v} value={v}><div className="main-grid" aria-live="polite"><section><div className="eyebrow">{day==='0'?'The rest of your day':'A look at tomorrow'}</div><h2 className="headline">{advice.headline.split('\n').map((s,i)=><span key={s}>{i>0&&<br/>}{s}</span>)}</h2><p className="summary">{advice.summary}</p><div className="advice"><div className="advice-row"><Umbrella/>{advice.umbrella}</div><div className="advice-row"><Shirt/>{advice.clothes}</div><div className="advice-row"><Sunset/>{advice.eveningText}</div></div></section><aside className="aside"><div className="current"><WeatherIcon aria-hidden="true"/><div><div className="temperature">{day==='0'?Math.round(forecast.current.temperature_2m):advice.feels}°<span style={{fontSize:18,letterSpacing:0}}>C</span></div><div className="muted">{day==='0'?`${conditions(forecast.current.weather_code)} · feels ${Math.round(forecast.current.apparent_temperature)}°`:`Feels like ${advice.low}–${advice.feels}°`}</div></div></div><div className="outing"><div className="eyebrow"><Clock3/>Best time to head out</div><h2>{advice.window}</h2><p>{advice.windowNote}</p></div><p className="uncertainty">Hourly estimates, not a promise. Check again before you leave.</p></aside></div></TabsContent>)}</Tabs>
 <details className="forecast-details"><summary>Hourly forecast &amp; details <ChevronDown aria-hidden="true" size={18}/></summary><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Weather</TableHead><TableHead>Temp.</TableHead><TableHead>Feels</TableHead><TableHead>Rain chance</TableHead><TableHead>Wind</TableHead></TableRow></TableHeader><TableBody>{advice.hours.map(h=><TableRow key={h.time}><TableCell>{hourLabel(h.time)}</TableCell><TableCell>{conditions(h.code)}</TableCell><TableCell>{Math.round(h.temp)}°C</TableCell><TableCell>{Math.round(h.feels)}°C</TableCell><TableCell>{h.rain}%</TableCell><TableCell>{Math.round(h.wind)} km/h</TableCell></TableRow>)}</TableBody></Table><p className="muted" style={{marginTop:18}}>Rain chance is the probability of precipitation, not how long it will rain. Times are local to {place.name}. Advice uses forecast-based rules.</p></details></div>:<section className="welcome" aria-live="polite"><div className="eyebrow">Your day, translated</div><h2 className="headline">{loading?'Getting a read on your day.':forecast?'A new day is here.':'Let’s find your forecast.'}</h2><p>{loading?`Checking the forecast for ${place.name}…`:forecast?'Refresh for today’s latest weather.':'Search for a city or use your location to see what to wear, what to bring, and when to head out.'}</p>{!loading&&<button className="quiet-button" onClick={()=>load(place)}><RefreshCw/>Refresh forecast</button>}</section>}
 <footer className="footer"><span className="updated"><span className="dot"/>{loading?'Updating…':forecast?`${stale?'Last successful update':'Updated'} ${new Intl.DateTimeFormat('en',{timeZone:forecast.timezone,hour:'numeric',minute:'2-digit'}).format(new Date(forecast.fetchedAt))}`:'Waiting for forecast'}{forecast&&<button aria-label="Refresh forecast" onClick={()=>load(place)} disabled={loading}><RefreshCw size={13}/></button>}</span><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather data by Open-Meteo ↗</a></footer>
 </div></main>;
}
